load("@rules_vhdl//vhdl:defs.bzl", "vhdl_library")

# gazelle:orbit_tags no-lint,no-format

vhdl_library(
    name = "nand_gate",
    srcs = ["nand_gate.vhd"],
    library = "gates",
    tags = [
        "no-format",
        "no-lint",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//primitives:and_gate",
        "//primitives:inverter",
    ],
)

vhdl_library(
    name = "or_gate",
    srcs = ["or_gate.vhd"],
    library = "gates",
    tags = [
        "no-format",
        "no-lint",
    ],
    visibility = ["//visibility:public"],
)
