exports_files([
    "LICENSE",
    "MODULE.bazel",
    "version.bzl",
])

alias(
    name = "orbit",
    actual = "@orbit//:orbit",
    visibility = ["//visibility:public"],
)

alias(
    name = "orbit_cli",
    actual = ":orbit",
    visibility = ["//visibility:public"],
)

alias(
    name = "gazelle_orbit",
    actual = "//gazelle:gazelle_orbit",
    visibility = ["//visibility:public"],
)
